2025-04-27 16:19:58,630 - app_logger - ERROR - Error writing data
Traceback (most recent call last):
  File "/app/app/crud.py", line 7, in write_data
    redis = get_redis_client()
            ^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 16:19:58,631 - app_logger - ERROR - Error writting data: Redis is not initialized!
2025-04-27 16:19:58,632 - app_logger - INFO - POST http://testserver/write_data -> 500
2025-04-27 16:19:58,647 - app_logger - ERROR - Error geting data for phone
Traceback (most recent call last):
  File "/app/app/crud.py", line 16, in get_address
    redis = await get_redis_client()
                  ^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 16:19:58,648 - app_logger - ERROR - Error getting data for phone: 404: Phone number not found
2025-04-27 16:19:58,648 - app_logger - INFO - GET http://testserver/check_data?phone=1234567890 -> 500
2025-04-27 16:20:35,929 - app_logger - ERROR - Error writing data
Traceback (most recent call last):
  File "/app/app/crud.py", line 7, in write_data
    redis = get_redis_client()
            ^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 16:20:35,930 - app_logger - ERROR - Error writting data: Redis is not initialized!
2025-04-27 16:20:35,930 - app_logger - INFO - POST http://testserver/write_data -> 500
2025-04-27 16:20:35,941 - app_logger - ERROR - Error geting data for phone
Traceback (most recent call last):
  File "/app/app/crud.py", line 16, in get_address
    redis = await get_redis_client()
                  ^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 16:20:35,941 - app_logger - ERROR - Error getting data for phone: 404: Phone number not found
2025-04-27 16:20:35,941 - app_logger - INFO - GET http://testserver/check_data?phone=1234567890 -> 500
2025-04-27 16:21:08,591 - app_logger - ERROR - Error writing data
Traceback (most recent call last):
  File "/app/app/crud.py", line 7, in write_data
    redis = get_redis_client()
            ^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 16:21:08,592 - app_logger - ERROR - Error writting data: Redis is not initialized!
2025-04-27 16:21:08,593 - app_logger - INFO - POST http://testserver/write_data -> 500
2025-04-27 16:21:08,603 - app_logger - ERROR - Error geting data for phone
Traceback (most recent call last):
  File "/app/app/crud.py", line 16, in get_address
    redis = await get_redis_client()
                  ^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 16:21:08,603 - app_logger - ERROR - Error getting data for phone: 404: Phone number not found
2025-04-27 16:21:08,603 - app_logger - INFO - GET http://testserver/check_data?phone=1234567890 -> 500
2025-04-27 16:21:47,379 - app_logger - ERROR - Error writing data
Traceback (most recent call last):
  File "/app/app/crud.py", line 7, in write_data
    redis = get_redis_client()
            ^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 16:21:47,380 - app_logger - ERROR - Error writting data: Redis is not initialized!
2025-04-27 16:21:47,380 - app_logger - INFO - POST http://testserver/write_data -> 500
2025-04-27 16:21:47,389 - app_logger - ERROR - Error geting data for phone
Traceback (most recent call last):
  File "/app/app/crud.py", line 16, in get_address
    redis = await get_redis_client()
                  ^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 16:21:47,389 - app_logger - ERROR - Error getting data for phone: 404: Phone number not found
2025-04-27 16:21:47,390 - app_logger - INFO - GET http://testserver/check_data?phone=1234567890 -> 500
2025-04-27 16:26:52,661 - app_logger - ERROR - Error writing data
Traceback (most recent call last):
  File "/app/app/crud.py", line 7, in write_data
    redis = get_redis_client()
            ^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 16:26:52,662 - app_logger - ERROR - Error writting data: Redis is not initialized!
2025-04-27 16:26:52,662 - app_logger - INFO - POST http://testserver/write_data -> 500
2025-04-27 16:26:52,675 - app_logger - ERROR - Error geting data for phone
Traceback (most recent call last):
  File "/app/app/crud.py", line 16, in get_address
    redis = await get_redis_client()
                  ^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 16:26:52,675 - app_logger - ERROR - Error getting data for phone: 404: Phone number not found
2025-04-27 16:26:52,675 - app_logger - INFO - GET http://testserver/check_data?phone=1234567890 -> 500
2025-04-27 16:29:10,739 - app_logger - ERROR - Error writing data
Traceback (most recent call last):
  File "/app/app/crud.py", line 7, in write_data
    redis = get_redis_client()
            ^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 16:29:10,740 - app_logger - ERROR - Error writting data: Redis is not initialized!
2025-04-27 16:29:10,740 - app_logger - INFO - POST http://testserver/write_data -> 500
2025-04-27 16:29:10,750 - app_logger - ERROR - Error geting data for phone
Traceback (most recent call last):
  File "/app/app/crud.py", line 16, in get_address
    redis = await get_redis_client()
                  ^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 16:29:10,750 - app_logger - ERROR - Error getting data for phone: 404: Phone number not found
2025-04-27 16:29:10,750 - app_logger - INFO - GET http://testserver/check_data?phone=1234567890 -> 500
2025-04-27 16:32:41,978 - app_logger - ERROR - Error writing data
Traceback (most recent call last):
  File "/app/app/crud.py", line 8, in write_data
    await redis.set(phone, address)
          ^^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'set'
2025-04-27 16:32:41,979 - app_logger - ERROR - Error writting data: 'coroutine' object has no attribute 'set'
2025-04-27 16:32:41,979 - app_logger - INFO - POST http://testserver/write_data -> 500
2025-04-27 16:32:41,994 - app_logger - ERROR - Error geting data for phone
Traceback (most recent call last):
  File "/app/app/crud.py", line 16, in get_address
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 16:32:41,994 - app_logger - ERROR - Error getting data for phone: 404: Phone number not found
2025-04-27 16:32:41,995 - app_logger - INFO - GET http://testserver/check_data?phone=1234567890 -> 500
2025-04-27 16:37:58,860 - app_logger - ERROR - Error writing data
Traceback (most recent call last):
  File "/app/app/crud.py", line 8, in write_data
    await redis.set(phone, address)
          ^^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'set'
2025-04-27 16:37:58,861 - app_logger - ERROR - Error writting data: 'coroutine' object has no attribute 'set'
2025-04-27 16:37:58,861 - app_logger - INFO - POST http://testserver/write_data -> 500
2025-04-27 16:37:58,876 - app_logger - ERROR - Error geting data for phone
Traceback (most recent call last):
  File "/app/app/crud.py", line 16, in get_address
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 16:37:58,877 - app_logger - ERROR - Error getting data for phone: 404: Phone number not found
2025-04-27 16:37:58,877 - app_logger - INFO - GET http://testserver/check_data?phone=1234567890 -> 500
2025-04-27 16:38:58,930 - app_logger - ERROR - Error writing data
Traceback (most recent call last):
  File "/app/app/crud.py", line 8, in write_data
    await redis.set(phone, address)
          ^^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'set'
2025-04-27 16:38:58,932 - app_logger - ERROR - Error writting data: 'coroutine' object has no attribute 'set'
2025-04-27 16:38:58,932 - app_logger - INFO - POST http://localhost:8000/write_data -> 500
2025-04-27 16:40:16,711 - app_logger - ERROR - Error writing data
Traceback (most recent call last):
  File "/app/app/crud.py", line 8, in write_data
    await redis.set(phone, address)
          ^^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'set'
2025-04-27 16:40:16,715 - app_logger - ERROR - Error writting data: 'coroutine' object has no attribute 'set'
2025-04-27 16:40:16,715 - app_logger - INFO - POST http://localhost:8000/write_data -> 500
2025-04-27 16:42:49,593 - app_logger - INFO - POST http://localhost:8000/write_data -> 201
2025-04-27 16:47:46,461 - app_logger - ERROR - Error writing data
Traceback (most recent call last):
  File "/app/app/crud.py", line 7, in write_data
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 16:47:46,462 - app_logger - ERROR - Error writting data: Redis is not initialized!
2025-04-27 16:47:46,462 - app_logger - INFO - POST http://testserver/write_data -> 500
2025-04-27 16:47:46,470 - app_logger - ERROR - Error geting data for phone
Traceback (most recent call last):
  File "/app/app/crud.py", line 16, in get_address
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 16:47:46,471 - app_logger - ERROR - Error getting data for phone: 404: Phone number not found
2025-04-27 16:47:46,471 - app_logger - INFO - GET http://testserver/check_data?phone=1234567890 -> 500
2025-04-27 16:48:04,452 - app_logger - INFO - POST http://localhost:8000/write_data -> 201
2025-04-27 16:54:02,041 - app_logger - INFO - GET http://localhost:8000/check_data/phone=82345678905 -> 404
2025-04-27 16:54:47,228 - app_logger - INFO - GET http://localhost:8000/check_data?phone=82345678905 -> 200
2025-04-27 16:59:12,997 - app_logger - ERROR - Error writing data
Traceback (most recent call last):
  File "/app/app/crud.py", line 7, in write_data
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 16:59:12,998 - app_logger - ERROR - Error writting data: Redis is not initialized!
2025-04-27 16:59:12,998 - app_logger - INFO - POST http://testserver/write_data -> 500
2025-04-27 16:59:13,006 - app_logger - ERROR - Error geting data for phone
Traceback (most recent call last):
  File "/app/app/crud.py", line 16, in get_address
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 16:59:13,006 - app_logger - ERROR - Error getting data for phone: 404: Phone number not found
2025-04-27 16:59:13,006 - app_logger - INFO - GET http://testserver/check_data?phone=1234567890 -> 500
2025-04-27 17:13:03,870 - app_logger - ERROR - Error writing data
Traceback (most recent call last):
  File "/app/app/crud.py", line 7, in write_data
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 17:13:03,871 - app_logger - ERROR - Error writting data: Redis is not initialized!
2025-04-27 17:13:03,871 - app_logger - INFO - POST http://testserver/write_data -> 500
2025-04-27 17:13:03,880 - app_logger - ERROR - Error geting data for phone
Traceback (most recent call last):
  File "/app/app/crud.py", line 16, in get_address
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 17:13:03,880 - app_logger - ERROR - Error getting data for phone: 404: Phone number not found
2025-04-27 17:13:03,881 - app_logger - INFO - GET http://testserver/check_data?phone=1234567890 -> 500
2025-04-27 17:15:27,508 - app_logger - ERROR - Error writing data
Traceback (most recent call last):
  File "/app/app/crud.py", line 7, in write_data
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 17:15:27,509 - app_logger - ERROR - Error writting data: Redis is not initialized!
2025-04-27 17:15:27,509 - app_logger - INFO - POST http://testserver/write_data -> 500
2025-04-27 17:15:27,518 - app_logger - ERROR - Error geting data for phone
Traceback (most recent call last):
  File "/app/app/crud.py", line 16, in get_address
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 17:15:27,518 - app_logger - ERROR - Error getting data for phone: 404: Phone number not found
2025-04-27 17:15:27,518 - app_logger - INFO - GET http://testserver/check_data?phone=1234567890 -> 500
2025-04-27 17:21:50,222 - app_logger - ERROR - Error writing data
Traceback (most recent call last):
  File "/app/app/crud.py", line 7, in write_data
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 17:21:50,225 - app_logger - ERROR - Error writting data: Redis is not initialized!
2025-04-27 17:21:50,226 - app_logger - INFO - POST http://testserver/write_data -> 500
2025-04-27 17:21:50,234 - app_logger - ERROR - Error geting data for phone
Traceback (most recent call last):
  File "/app/app/crud.py", line 16, in get_address
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 17:21:50,235 - app_logger - ERROR - Error getting data for phone: 404: Phone number not found
2025-04-27 17:21:50,235 - app_logger - INFO - GET http://testserver/check_data?phone=1234567890 -> 500
2025-04-27 17:26:22,127 - app_logger - ERROR - Error writing data
Traceback (most recent call last):
  File "/app/app/crud.py", line 7, in write_data
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 17:26:22,127 - app_logger - ERROR - Error writting data: Redis is not initialized!
2025-04-27 17:26:22,128 - app_logger - INFO - POST http://testserver/write_data -> 500
2025-04-27 17:26:22,136 - app_logger - ERROR - Error geting data for phone
Traceback (most recent call last):
  File "/app/app/crud.py", line 16, in get_address
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 17:26:22,137 - app_logger - ERROR - Error getting data for phone: 404: Phone number not found
2025-04-27 17:26:22,137 - app_logger - INFO - GET http://testserver/check_data?phone=1234567890 -> 500
2025-04-27 18:11:25,966 - app_logger - ERROR - Error writing data
Traceback (most recent call last):
  File "/app/app/crud.py", line 7, in write_data
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 18:11:25,967 - app_logger - ERROR - Error writting data: Redis is not initialized!
2025-04-27 18:11:25,967 - app_logger - INFO - POST http://testserver/write_data -> 500
2025-04-27 18:11:25,976 - app_logger - ERROR - Error geting data for phone
Traceback (most recent call last):
  File "/app/app/crud.py", line 16, in get_address
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 18:11:25,976 - app_logger - ERROR - Error getting data for phone: 404: Phone number not found
2025-04-27 18:11:25,976 - app_logger - INFO - GET http://testserver/check_data?phone=1234567890 -> 500
2025-04-27 18:17:54,940 - app_logger - ERROR - Error writing data
Traceback (most recent call last):
  File "/app/app/crud.py", line 7, in write_data
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 18:17:54,941 - app_logger - ERROR - Error writting data: Redis is not initialized!
2025-04-27 18:17:54,942 - app_logger - INFO - POST http://testserver/write_data -> 500
2025-04-27 18:17:54,950 - app_logger - ERROR - Error geting data for phone
Traceback (most recent call last):
  File "/app/app/crud.py", line 16, in get_address
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 18:17:54,950 - app_logger - ERROR - Error getting data for phone: 404: Phone number not found
2025-04-27 18:17:54,951 - app_logger - INFO - GET http://testserver/check_data?phone=1234567890 -> 500
2025-04-27 18:20:24,826 - app_logger - ERROR - Error writing data
Traceback (most recent call last):
  File "/app/app/crud.py", line 7, in write_data
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 18:20:24,827 - app_logger - ERROR - Error writting data: Redis is not initialized!
2025-04-27 18:20:24,827 - app_logger - INFO - POST http://testserver/write_data -> 500
2025-04-27 18:20:24,836 - app_logger - ERROR - Error geting data for phone
Traceback (most recent call last):
  File "/app/app/crud.py", line 16, in get_address
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 18:20:24,836 - app_logger - ERROR - Error getting data for phone: 404: Phone number not found
2025-04-27 18:20:24,836 - app_logger - INFO - GET http://testserver/check_data?phone=1234567890 -> 500
2025-04-27 18:23:55,837 - app_logger - ERROR - Error writing data
Traceback (most recent call last):
  File "/app/app/crud.py", line 7, in write_data
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 18:23:55,838 - app_logger - ERROR - Error writting data: Redis is not initialized!
2025-04-27 18:23:55,839 - app_logger - INFO - POST http://testserver/write_data -> 500
2025-04-27 18:23:55,847 - app_logger - ERROR - Error geting data for phone
Traceback (most recent call last):
  File "/app/app/crud.py", line 16, in get_address
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 18:23:55,847 - app_logger - ERROR - Error getting data for phone: 404: Phone number not found
2025-04-27 18:23:55,847 - app_logger - INFO - GET http://testserver/check_data?phone=1234567890 -> 500
2025-04-27 18:25:35,766 - app_logger - ERROR - Error writing data
Traceback (most recent call last):
  File "/app/app/crud.py", line 7, in write_data
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 18:25:35,767 - app_logger - ERROR - Error writting data: Redis is not initialized!
2025-04-27 18:25:35,767 - app_logger - INFO - POST http://testserver/write_data -> 500
2025-04-27 18:25:35,775 - app_logger - ERROR - Error geting data for phone
Traceback (most recent call last):
  File "/app/app/crud.py", line 16, in get_address
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 18:25:35,775 - app_logger - ERROR - Error getting data for phone: 404: Phone number not found
2025-04-27 18:25:35,776 - app_logger - INFO - GET http://testserver/check_data?phone=1234567890 -> 500
2025-04-27 18:27:57,093 - app_logger - ERROR - Error writing data
Traceback (most recent call last):
  File "/app/app/crud.py", line 7, in write_data
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 18:27:57,094 - app_logger - ERROR - Error writting data: Redis is not initialized!
2025-04-27 18:27:57,094 - app_logger - INFO - POST http://testserver/write_data -> 500
2025-04-27 18:27:57,104 - app_logger - ERROR - Error geting data for phone
Traceback (most recent call last):
  File "/app/app/crud.py", line 16, in get_address
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 18:27:57,104 - app_logger - ERROR - Error getting data for phone: 404: Phone number not found
2025-04-27 18:27:57,104 - app_logger - INFO - GET http://testserver/check_data?phone=1234567890 -> 500
2025-04-27 18:37:29,049 - app_logger - ERROR - Error writing data
Traceback (most recent call last):
  File "/app/app/crud.py", line 7, in write_data
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 18:37:29,051 - app_logger - ERROR - Error writting data: Redis is not initialized!
2025-04-27 18:37:29,051 - app_logger - INFO - POST http://testserver/write_data -> 500
2025-04-27 18:37:29,059 - app_logger - ERROR - Error geting data for phone
Traceback (most recent call last):
  File "/app/app/crud.py", line 16, in get_address
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 18:37:29,059 - app_logger - ERROR - Error getting data for phone: 404: Phone number not found
2025-04-27 18:37:29,059 - app_logger - INFO - GET http://testserver/check_data?phone=1234567890 -> 500
2025-04-27 19:57:54,473 - app_logger - ERROR - Error writing data
Traceback (most recent call last):
  File "/app/app/crud.py", line 7, in write_data
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 19:57:54,473 - app_logger - ERROR - Error writting data: Redis is not initialized!
2025-04-27 19:57:54,474 - app_logger - INFO - POST http://testserver/write_data -> 500
2025-04-27 19:57:54,481 - app_logger - ERROR - Error geting data for phone
Traceback (most recent call last):
  File "/app/app/crud.py", line 16, in get_address
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 19:57:54,481 - app_logger - ERROR - Error getting data for phone: 404: Phone number not found
2025-04-27 19:57:54,481 - app_logger - INFO - GET http://testserver/check_data?phone=1234567890 -> 500
2025-04-27 20:20:00,752 - app_logger - INFO - POST http://localhost:8000/write_data -> 201
2025-04-27 20:20:15,225 - app_logger - INFO - GET http://localhost:8000/check_data?phone=82345678905 -> 200
2025-04-27 22:32:47,585 - app_logger - ERROR - Error writing data
Traceback (most recent call last):
  File "/Users/nikitaminenkov/PycharmProjects/fastapi_service/app/crud.py", line 7, in write_data
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikitaminenkov/PycharmProjects/fastapi_service/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 22:32:47,586 - app_logger - ERROR - Error writting data: Redis is not initialized!
2025-04-27 22:32:47,586 - app_logger - INFO - POST http://test/write_data -> 500
2025-04-27 22:32:47,598 - app_logger - ERROR - Error writing data
Traceback (most recent call last):
  File "/Users/nikitaminenkov/PycharmProjects/fastapi_service/app/crud.py", line 7, in write_data
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikitaminenkov/PycharmProjects/fastapi_service/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 22:32:47,598 - app_logger - ERROR - Error writting data: Redis is not initialized!
2025-04-27 22:32:47,598 - app_logger - INFO - POST http://test/write_data -> 500
2025-04-27 22:32:47,599 - app_logger - ERROR - Error writing data
Traceback (most recent call last):
  File "/Users/nikitaminenkov/PycharmProjects/fastapi_service/app/crud.py", line 7, in write_data
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikitaminenkov/PycharmProjects/fastapi_service/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 22:32:47,599 - app_logger - ERROR - Error writting data: Redis is not initialized!
2025-04-27 22:32:47,599 - app_logger - INFO - POST http://test/write_data -> 500
2025-04-27 22:32:47,601 - app_logger - ERROR - Error writing data
Traceback (most recent call last):
  File "/Users/nikitaminenkov/PycharmProjects/fastapi_service/app/crud.py", line 7, in write_data
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikitaminenkov/PycharmProjects/fastapi_service/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 22:32:47,601 - app_logger - ERROR - Error writting data: Redis is not initialized!
2025-04-27 22:32:47,601 - app_logger - INFO - POST http://test/write_data -> 500
2025-04-27 22:32:47,602 - app_logger - ERROR - Error geting data for phone
Traceback (most recent call last):
  File "/Users/nikitaminenkov/PycharmProjects/fastapi_service/app/crud.py", line 16, in get_address
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikitaminenkov/PycharmProjects/fastapi_service/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 22:32:47,602 - app_logger - ERROR - Error getting data for phone: 404: Phone number not found
2025-04-27 22:32:47,602 - app_logger - INFO - GET http://test/check_data?phone=89090000002 -> 500
2025-04-27 22:32:47,604 - app_logger - ERROR - Error geting data for phone
Traceback (most recent call last):
  File "/Users/nikitaminenkov/PycharmProjects/fastapi_service/app/crud.py", line 16, in get_address
    redis = await get_redis_client()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikitaminenkov/PycharmProjects/fastapi_service/app/redis_client.py", line 25, in get_redis_client
    raise Exception("Redis is not initialized!")
Exception: Redis is not initialized!
2025-04-27 22:32:47,604 - app_logger - ERROR - Error getting data for phone: 404: Phone number not found
2025-04-27 22:32:47,604 - app_logger - INFO - GET http://test/check_data?phone=00000000000 -> 500
2025-04-27 22:32:47,606 - app_logger - INFO - POST http://test/write_data -> 422
2025-04-27 22:32:47,607 - app_logger - INFO - POST http://test/write_data -> 422
2025-04-27 22:32:47,608 - app_logger - INFO - GET http://test/check_data -> 422
2025-04-27 20:52:00,282 - app_logger - INFO - GET http://localhost:8000/healthcheck -> 404
2025-04-27 20:52:09,976 - app_logger - INFO - GET http://localhost:8000/health -> 200
2025-04-27 20:53:49,936 - app_logger - INFO - POST http://localhost:8000/write_data -> 201
2025-04-27 20:59:24,866 - app_logger - INFO - POST http://localhost:8000/write_data -> 201
2025-04-27 20:59:55,238 - app_logger - INFO - GET http://localhost:8000/health -> 200
2025-04-27 21:00:11,746 - app_logger - INFO - GET http://localhost:8000/check_data?phone=82345678905 -> 200
2025-04-27 21:08:18,833 - app_logger - INFO - POST http://localhost:8000/write_data -> 201
2025-04-27 21:08:31,457 - app_logger - INFO - POST http://localhost:8000/write_data -> 201
2025-04-27 21:10:14,927 - app_logger - INFO - POST http://localhost:8000/write_data -> 201
2025-04-27 21:10:22,660 - app_logger - WARNING - Attempt to create existing phone number: 82345678905
2025-04-27 21:10:22,661 - app_logger - ERROR - Error writting data: Phone number 82345678905 already exists
2025-04-27 21:10:22,661 - app_logger - INFO - POST http://localhost:8000/write_data -> 500
2025-04-27 21:10:37,683 - app_logger - WARNING - Attempt to create existing phone number: 82345678905
2025-04-27 21:10:37,684 - app_logger - ERROR - Error writting data: Phone number 82345678905 already exists
2025-04-27 21:10:37,686 - app_logger - INFO - POST http://localhost:8000/write_data -> 500
2025-04-27 21:10:48,866 - app_logger - INFO - POST http://localhost:8000/write_data -> 201
2025-04-27 21:17:38,409 - app_logger - INFO - Phone 82345678905 updated in Redis.
2025-04-27 21:17:38,410 - app_logger - INFO - POST http://localhost:8000/write_data -> 201
2025-04-27 21:19:03,338 - app_logger - INFO - Phone 82345678905 updated in Redis.
2025-04-27 21:19:03,341 - app_logger - INFO - POST http://localhost:8000/write_data -> 201
2025-04-27 21:19:17,070 - app_logger - INFO - Phone 82345673905 created in Redis.
2025-04-27 21:19:17,071 - app_logger - INFO - POST http://localhost:8000/write_data -> 201
2025-04-27 21:19:36,267 - app_logger - INFO - Phone 82345673905 updated in Redis.
2025-04-27 21:19:36,268 - app_logger - INFO - POST http://localhost:8000/write_data -> 201
2025-04-27 21:19:45,885 - app_logger - INFO - Phone 82345673605 created in Redis.
2025-04-27 21:19:45,888 - app_logger - INFO - POST http://localhost:8000/write_data -> 201
2025-04-27 21:20:10,429 - app_logger - INFO - GET http://localhost:8000/check_data?phone=82345673605 -> 200
